/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://alytwqupmrbpnhyordvc5xqgde.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zg2h7ju6ljaqldq6zebvnlkvka",
    "aws_cognito_identity_pool_id": "us-west-2:0a802c0f-368d-4e6b-bdfd-58952677e6ea",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Ke6moL9HA",
    "aws_user_pools_web_client_id": "47neoqcphpp8nhos5bqom32o8e",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "items-dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
